devices:
  test1:
    address: 192.168.1.1
    user: foo
    password: bar
    schema: https
  test2:
    address: 192.168.2.1
    user: test
    password: 123
    schema: https

features:
  hwmon: true
  poe: true
